### ISSUE TITLE
Add full libmagic description string

### ISSUE THREAD

**Issue by knowmalware** [maliceio/malice#28]
The libmagic full description string contains more information than just the mimetype.  For example, it indicates multi-typed files, such as self-executing (SFX) archives.

Here is what I am thinking: 530a256

I am not a go coder, so may have done that wrong.  Still figuring out how to test my changes.

**Comment by blacktop** [comment]
I like that idea.  I was only using libmagic to decide how to filter the plugins so I don't do something dumb like was time running a Pexe plugin on a Word Doc, but since I have a hold of the file I should pull that info out.  Also the mimetype might not have enough granularity for me to really decide what tool to use.  example: RTF or OLE etc etc
