### ISSUE TITLE
Newer version of malice config.toml available: 0.3.2  Would you like to update now? (yes/no)

### ISSUE THREAD

**Issue by dsslimshaddy** [maliceio/malice#55]
always showing this message whenever i want to scan

Newer version of malice config.toml available: 0.3.2 
Would you like to update now? (yes/no)

is there any way to not show it

**Comment by blacktop** [comment]
can you tell me where you are running it from? `which malice` 

I think you might have an older version you built from source in your $GOPATH/bin folder that is running instead of a newer version that fixed that config bug.

I apologize and am re-writting malice which will fix a LOT of things one of them being the config mess

**Comment by dsslimshaddy** [comment]
Sorry. i installed an old version using because of  https://github.com/maliceio/malice/blob/master/docs/installation/linux/install.md
i installed `v0.3.2` instead of  `v0.3.11`.

**Comment by blacktop** [comment]
I updated the install docs -

https://github.com/maliceio/malice/blob/master/docs/installation/linux/install.md
